### ISSUE TITLE
Implement Build Provenance Attestation for Releases

### ISSUE THREAD

**Issue by gaspard-lebaube** [gaskam/workspace#24]
To enhance the security and transparency of our releases, we need to implement **build provenance attestation** using GitHub Actions. This will allow users to verify that the binaries in our releases were built from the exact source code in this repository and follow a trusted build process.

### Objectives
1. Integrate the [`actions/attest-build-provenance`](https://github.com/actions/attest-build-provenance) action into our existing build workflow.
2. Generate signed attestations for all executables produced by `zig build`.
3. Include a link to the attestations in the release notes.
4. Provide clear instructions for users to verify the provenance of the binaries.

```bash
gh attestation verify [file] --owner gaskam
```

**Comment by gaspard-lebaube** [comment]
Provenance attestation added on commit [b5490fd](https://github.com/gaskam/workspace/commit/b5490fd07b1048a7c7b9ba9544b962c6171e5c70) : 
```yml
@@ -16,6 +16,11 @@ jobs:
build:
runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

steps:
- name: Checkout repository
uses: actions/checkout@v4.2.2
@@ -44,6 +49,12 @@
         zvm use $ZIG_VERSION
         zig build

      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2.2.0
        with:
          subject-path: './zig-out/*'
          show-summary: true

- name: Install Zip
run: sudo apt-get install -y zip

@@ -114,6 +125,7 @@
- name: Add release installation instructions
run: |
         EXISTING_NOTES=$(gh release view $TAG_NAME --json body -q .body)
          ATTESTATION_LINK="https://github.com/${{ github.repository }}/attestations"
         INSTALL_NOTES="You can install the latest version (${TAG_NAME}) with the commands below:

         For **Linux**:
@@ -131,6 +143,13 @@
         workspace update
         \`\`\`

          The binaries in this release are signed and verifiable via [GitHub Attestations](${ATTESTATION_LINK}).

          You can check the certificates with:
          \`\`\`bash
          gh attestation verify [fichier] --owner gaskam
          \`\`\`

         $EXISTING_NOTES"
         gh release edit $TAG_NAME --notes "$INSTALL_NOTES"
       env:
```
